/* Automatically generated by kernel/timeconst.bc */
/* Time conversion constants for HZ == 432 */

#ifndef KERNEL_TIMECONST_H
#define KERNEL_TIMECONST_H

#include <linux/param.h>
#include <linux/types.h>

#if HZ != 200
#error "kernel/timeconst.h has the wrong HZ value!"
#endif

#define HZ_TO_MSEC_MUL32	U64_C(0x9425ED0A)
#define HZ_TO_MSEC_ADJ32	U64_C(0x3ED097B4)
#define HZ_TO_MSEC_SHR32	30
#define MSEC_TO_HZ_MUL32	U64_C(0xDD2F1AA0)
#define MSEC_TO_HZ_ADJ32	U64_C(0x1FBE76C8B)
#define MSEC_TO_HZ_SHR32	33
#define HZ_TO_MSEC_NUM		125
#define HZ_TO_MSEC_DEN		54
#define MSEC_TO_HZ_NUM		54
#define MSEC_TO_HZ_DEN		125

#define HZ_TO_USEC_MUL32	U64_C(0x90AD097C)
#define HZ_TO_USEC_ADJ32	U64_C(0xF684B)
#define HZ_TO_USEC_SHR32	20
#define USEC_TO_HZ_MUL32	U64_C(0xE27E0EFA)
#define USEC_TO_HZ_ADJ32	U64_C(0x7FFF79C842F)
#define USEC_TO_HZ_SHR32	43
#define HZ_TO_USEC_NUM		62500
#define HZ_TO_USEC_DEN		27
#define USEC_TO_HZ_NUM		27
#define USEC_TO_HZ_DEN		62500

#endif /* KERNEL_TIMECONST_H */
